name: Auto-Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0,2,4"

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    outputs:
      deploy: ${{ steps.commit.outputs.deploy }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Build & Run
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn run start:dev

      - name: Commit changes
        id: commit
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Committing changes."
            echo "{deploy}={true}" >> $GITHUB_OUTPUT
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Stations Auto-Update (`date`)" -a || true
            git push
          else
            echo "No changes."
            echo "{deploy}={false}" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    name: Deploy
    needs: build
    if: needs.build.outputs.deploy == 'true' || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
