name: Update stations

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0,2,5'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Update stations
      run: |
        npm ci
        npm run start:dev   
    
    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Stations Auto-Update (`date`)" -a || true
        git push
