name: Auto-Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0,2,4"

jobs:
  update:
    name: Update & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Build & Run
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn run start:dev

      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Commiting changes."
            echo "DEPLOY=true" >> $GITHUB_ENV
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Stations Auto-Update (`date`)" -a || true
            git push
          else
            echo "No changes."
            echo "DEPLOY=false" >> $GITHUB_ENV
          fi

      - name: Deploy page
        if: env.DEPLOY == 'true' || github.event_name == 'workflow_dispatch'
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          folder: pages
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
